import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Head from'next/head'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     <Head><link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'></link></Head> 
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header />
        {children}
        <footer className="fixed bottom-0 bg-black text-white row-start-3 flex gap-[24px] items-center justify-center w-full">
         <div>Lasted Update 8 / 4 / 2025</div>
      </footer>
      
      </body>
    </html>
  );
}
